const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');

let args;
let rpcError = null;
const exportsObject = {};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/services/notes.ts', 'utf8'), {
  compilerOptions: { module: ts.ModuleKind.CommonJS },
}).outputText, {
  exports: exportsObject,
  require: () => ({ supabase: { rpc: async (name, input) => {
    assert.ok(['save_shared_note', 'empty_notes_trash'].includes(name)); args = input;
    return { data: { ...input, version: 3 }, error: rpcError };
  } } }),
});

(async () => {
  const note = { id: 'note', couple_id: 'pair', kind: 'checklist', title: 'Покупки', body: '',
    items: [{ id: 'item', text: 'Чай', done: false }], pinned: false, deleted_at: null, version: 2 };
  await exportsObject.saveNote(note);
  assert.equal(args.p_version, 2, 'Must send expected version');
  assert.equal(args.p_couple_id, 'pair');
  assert.equal(args.p_items[0].done, false);
  assert.equal(args.p_deleted, false);
  await exportsObject.saveNote({ ...note, deleted_at: '2026-09-30' });
  assert.equal(args.p_deleted, true);
  await exportsObject.saveNote({ ...note, id: '', version: 0 });
  assert.equal(args.p_id, null, 'New note ID is generated by database');
  rpcError = { code: '40001', message: 'NOTE_CONFLICT' };
  await assert.rejects(exportsObject.saveNote(note), (error) => error.code === '40001');
  assert.equal(exportsObject.noteContent(note), exportsObject.noteContent({ ...note, version: 8 }), 'Version alone is not a user edit');
  for (const patch of [{ title: 'Другое' }, { body: 'Текст' }, { pinned: true }, { deleted_at: 'now' }, { items: [{ id: 'item', text: 'Чай', done: true }] }]) {
    assert.notEqual(exportsObject.noteContent(note), exportsObject.noteContent({ ...note, ...patch }));
  }
  const snapshot = { ...note, deleted_at: '2026-09-30T12:00:00.000Z' };
  const result = { ...snapshot, deleted_at: '2026-09-30T12:00:00+00:00', version: 3 };
  assert.equal(exportsObject.reconcileSavedNote(snapshot, snapshot, result), result, 'Adopt canonical timestamp to stop autosave');
  const merged = exportsObject.reconcileSavedNote({ ...snapshot, body: 'Typed during save' }, snapshot, result);
  assert.equal(merged.body, 'Typed during save');
  assert.equal(merged.version, 3);
  assert.equal(merged.deleted_at, result.deleted_at);
  rpcError = null;
  await exportsObject.emptyNotesTrash('pair', [note, result]);
  assert.equal(args.p_notes.length, 1, 'Active notes must not be submitted for permanent deletion');
  assert.equal(args.p_notes[0].version, 3, 'Only confirmed versions can be deleted');
  assert.equal(args.p_couple_id, 'pair');
  console.log('PASS: note content tracking, version forwarding, create, trash, conflict propagation');
})().catch((error) => { console.error(error); process.exitCode = 1; });
